

# **Question 5**

**Name:** Ankit BhagwatiPrasad Dhandharia

**CWID:** 20033031

In [5]:
# Importing all the required Library
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [6]:
df = pd.read_csv('hepatitis_B2.csv')
df.head()

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_BIG,LIVER_FIRM,SPLEEN_PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK_PHOSPHATE,SGOT,ALBUMIN,HISTOLOGY,Age_Quartile
0,1,39,1,1,1,1,1,2,2,1,2,2,2,2,2.3,280,98,3.8,1,Q2
1,1,37,1,2,2,1,2,2,2,2,2,1,2,2,0.6,67,28,4.2,1,Q2
2,1,58,1,2,2,1,2,2,1,1,1,1,2,2,2.0,167,242,3.3,1,Q4
3,1,30,1,2,2,1,1,1,2,1,2,1,1,1,2.5,165,64,2.8,2,Q1
4,1,38,1,1,2,1,1,1,2,1,2,1,1,1,1.2,118,16,2.8,2,Q2

In [7]:
df.describe()

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_BIG,LIVER_FIRM,SPLEEN_PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK_PHOSPHATE,SGOT,ALBUMIN,HISTOLOGY
count,40.000000,40.00000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000,40.000000,40.000000,40.000000
mean,1.525000,42.35000,1.100000,1.525000,1.775000,1.250000,1.600000,1.85000,1.825000,1.475000,1.825000,1.550000,1.750000,1.800000,1.490000,101.97500,71.825000,3.645000,1.425000
std,0.505736,11.86797,0.303822,0.505736,0.422902,0.438529,0.496139,0.36162,0.384808,0.505736,0.384808,0.503831,0.438529,0.405096,1.091647,51.05125,59.340775,0.651212,0.500641
min,1.000000,22.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.400000,45.00000,16.000000,2.100000,1.000000
25%,1.000000,33.75000,1.000000,1.000000,2.000000,1.000000,1.000000,2.00000,2.000000,1.000000,2.000000,1.000000,1.750000,2.000000,0.775000,66.50000,28.000000,3.250000,1.000000
50%,2.000000,40.50000,1.000000,2.000000,2.000000,1.000000,2.000000,2.00000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,1.100000,85.00000,54.000000,3.800000,1.000000
75%,2.000000,49.00000,1.000000,2.000000,2.000000,1.250000,2.000000,2.00000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,119.25000,91.250000,4.100000,2.000000
max,2.000000,78.00000,2.000000,2.000000,2.000000,2.000000,2.000000,2.00000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,4.800000,280.00000,249.000000,4.900000,2.000000

In [8]:
# Separate feature and label
features = df[["AGE", "SEX", "ASCITES", "BILIRUBIN", "ALK_PHOSPHATE", "SGOT", "ALBUMIN"]]
labels = df["Class"]
# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

In [10]:
for k in [1, 3, 5, 7]:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)  # Train the model on training data
    y_pred = knn.predict(X_test) # Predict on test data
    print("k=", k)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Classification Report", classification_report(y_test, y_pred))
    print("Confusion Matrix", confusion_matrix(y_test, y_pred))

k= 1
Accuracy: 0.625
Classification Report               precision    recall  f1-score   support

           1       0.67      0.50      0.57         4
           2       0.60      0.75      0.67         4

    accuracy                           0.62         8
   macro avg       0.63      0.62      0.62         8
weighted avg       0.63      0.62      0.62         8

Confusion Matrix [[2 2]
 [1 3]]
k= 3
Accuracy: 0.25
Classification Report               precision    recall  f1-score   support

           1       0.00      0.00      0.00         4
           2       0.33      0.50      0.40         4

    accuracy                           0.25         8
   macro avg       0.17      0.25      0.20         8
weighted avg       0.17      0.25      0.20         8

Confusion Matrix [[0 4]
 [2 2]]
k= 5
Accuracy: 0.25
Classification Report               precision    recall  f1-score   support

           1       0.00      0.00      0.00         4
           2       0.33      0.50      0.40         4

    accuracy                           0.25         8
   macro avg       0.17      0.25      0.20         8
weighted avg       0.17      0.25      0.20         8

Confusion Matrix [[0 4]
 [2 2]]
k= 7
Accuracy: 0.25
Classification Report               precision    recall  f1-score   support

           1       0.00      0.00      0.00         4
           2       0.33      0.50      0.40         4

    accuracy                           0.25         8
   macro avg       0.17      0.25      0.20         8
weighted avg       0.17      0.25      0.20         8

Confusion Matrix [[0 4]
 [2 2]]